### PR TITLE
Fix: Prevent UI reset when new device inserted during write (#825)

### LINKED ISSUE #825: Fedora Media Writer Pauses When Writing to Two Identical USB Drives
When writing to a USB drive using Fedora Media Writer, inserting another USB drive of the same kind causes the writing process to pause without any warning. The process resumes only after removing the newly inserted USB drive.

**Steps to Reproduce:**
1. Insert a SanDisk Cruzer Blade 15.7 GB USB drive into the system.
2. Open Fedora Media Writer (latest Flatpak version) and select the USB drive as the target.
3. Start the writing process.
4. While the writing process is ongoing, insert another SanDisk Cruzer Blade 15.7 GB USB drive.
5. Observe that the writing process pauses without notification.
6. Remove the newly inserted USB drive.
7. Observe that the writing process resumes automatically.

**Expected Behavior:**
- Fedora Media Writer should continue writing regardless of another identical USB being inserted.
- If there's an issue with multiple identical drives, a clear warning should be displayed instead of silently pausing.

**Actual Behavior:**
- The writing process pauses immediately when a second identical USB drive is inserted.
- No error message or indication is given.
- The process resumes only after removing the newly inserted USB drive.

**System Information:**
- **OS:** KDE Linux x86_64
- **Fedora Media Writer Version:** Latest Flatpak 5.2.3
- **USB Drive Model:** SanDisk Cruzer Blade 15.7 GB
- **System Hardware:** S6445 MD61489 (5.13_VEB_1AUOK026)

**Additional Notes:**
- This issue may be related to how Fedora Media Writer identifies and handles USB devices.
- Identification via `/dev/` remains unique (e.g., `sda` and `sdb` stay distinct), so this appears to be a logic bug where Fedora Media Writer may rely on the same label or another non-unique identifier despite different device nodes.
- It might be useful to test with different USB brands/models to determine if the issue occurs only with identical USBs or with multiple drives in general.

Would appreciate any insights or fixes for this issue. Thanks!

### PR DESCRIPTION
**Pull request by Prachi194agrawal**
When a new USB drive was inserted while another drive was being written to, the drive selection would automatically change to the newly inserted drive, causing the progress bar to disappear. The write process continued in the background, but users had no visual feedback.

This fix checks if the currently selected drive has an active write operation (progress > 0 and < drive size) before changing the selection. If a write is in progress, the selection remains unchanged when new drives are connected, preserving the progress display.

Fixes #825

### CODE REVIEW

**Comment by grulja** [comment]
Hi, thank you for your change. While I believe it fixes the issue, I have a slightly different solution in mind that I would like to apply instead, but it might require a bigger change. I will try to look into this as soon as possible.

**Comment by Prachi194agrawal** [comment]
Hi @grulja, thanks for the feedback!

I understand that you have a different approach in mind which may involve a larger change. If you have a moment, could you briefly explain the direction you’re considering (even at a high level)? That would help me understand the reasoning and see if I can either adjust my current fix or help work on the alternative solution.

Thanks again for taking a look!

**Comment by grulja** [comment]
Without further blocking this, I think there are two possible solutions:

- Either we stop changing the device selection once we insert a new device. I think this was done based on the assumption that the user will always want to automatically pick the newly inserted device. Instead I would only do just update of `m_selectedIndex` based on whether the new device is inserted to the list before the already selected device so you would just increment `m_selectedIndex` to still point to the same device.
- Maybe a better approach would be to implement something like `Drive::isBusy()`  that would track the state of the device. Since each operation (write or restore) creates and starts a QProcess and ends with `onFinished()` callback, you get the information when the operation ends. With that you can have something like:
```
// Moved up from the end of the function
if (d->restoreStatus() == Drive::CONTAINS_LIVE) {
    setLastRestoreable(d);
    connect(d, &Drive::restoreStatusChanged, [=]() {
        if (d && d == m_lastRestoreable && d->restoreStatus() != Drive::CONTAINS_LIVE)
            setLastRestoreable(nullptr);
    });
 } 

if (selected()->isBusy()) {
    return;
}

if (m_provider->initialized()) {
    m_selectedIndex = position;
    emit selectedChanged();
} else {
    m_selectedIndex = 0;
    emit selectedChanged();
}
```

What do you think? @gastoner any opinion?

**Comment by gastoner** [comment]
I would prefer the v2, liking the solution with `isBusy` function. This is probably easier to understand too, compared to switching indexes while being in some state etc...

**Comment by Prachi194agrawal** [comment]
Sir,
I've implemented the requested changes in commit 6d63fbc:
 Moved `QProcess *m_process` to the `Drive` base class (protected section)
Removed the local QProcess declarations from:
  - `LinuxDrive` (was `m_process`)
  - `MacDrive` (was `m_child`)  
  - `WinDrive` (was `m_child`)
Removed the manual `m_isBusy` boolean flag entirely
Implemented `Drive::isBusy()` to check the actual process state: 
   `return m_process && m_process->state() != QProcess::NotRunning;`
Refactored all platform implementations to use the inherited `m_process`

This provides a cleaner, state-based architecture as suggested. All platforms now share the same QProcess management logic, and busy status is determined by the actual process state rather than manual tracking.

Ready for review.

File: src/app/drivemanager.h [hunk 1]
```diff
@@ -194,6 +196,7 @@ public slots:
     RestoreStatus m_restoreStatus{CLEAN};
     QString m_error{};
     bool m_delayedWrite{false};
+    QProcess *m_process{nullptr};
```
Comment (grulja) [inline src/app/drivemanager.h]: Can we do here something like:
```
struct DriveOperationDeleter {
    void operator()(QProcess *process)  {
        if (!process) {
            return;
        }

        if (process->state() != QProcess::NotRunning) {
#ifdef Q_OS_WIN
            process->kill();
            process->waitForFinished();
#else
            process->terminate();
            if (!process->waitForFinished(3000)) {
                process->kill();
                process->waitForFinished();
            }
#endif
        }

        delete process;
    }
};

std::unique_ptr<QProcess, DriveOperationDeleter> m_process;
```

Then you can remove the `m_process` cleaning that is currently done separately in each `[Linux,Mac,Windows]DriveManager` destructor. Also you can simplify the process removal in each `cancel()` method and make the `DriveManager::cancel()` to simply do `m_process.reset()` that does exactly what we want thanks to the `DriveOperationDeleter`. With the use of `std::unique_ptr` you don't have to do:
``` 
if (m_process) {
    m_process->deleteLater();
}
m_process = new QProcess(this);
```
but simply:
```
m_process = std::make_unique<QProcess>(this);

File: src/app/drivemanager.cpp [hunk 2]
```diff
@@ -157,6 +157,12 @@ void DriveManager::onDriveConnected(Drive *d)
     endInsertRows();
     emit drivesChanged();
 
+    // Fix for issue #825: Only change selection if the currently selected drive is not busy
+    if (selected() && selected()->isBusy()) {
+        return;
+    }
+
+    // Standard logic: Select the new drive if not busy
```
Comment (grulja) [inline src/app/drivemanager.cpp]: Nit: this comment can be removed

File: src/app/linuxdrivemanager.cpp [hunk 3]
```diff
@@ -389,8 +382,7 @@ void LinuxDrive::onErrorOccurred(QProcess::ProcessError e)
     QString errorMessage = m_process->errorString();
     mWarning() << "Restoring failed:" << errorMessage;
     m_image->setErrorString(errorMessage);
-    m_process->deleteLater();
-    m_process = nullptr;
+    // Process cleanup handled automatically by unique_ptr deleter
```
Comment (grulja) [inline src/app/linuxdrivemanager.cpp]: Here we should also do `m_process.reset()`.

File: src/app/windrivemanager.cpp [hunk 4]
```diff
@@ -117,34 +117,25 @@ WinDrive::WinDrive(WinDriveProvider *parent, const QString &name, uint64_t size,
...
-    if (m_child) {
-        // TODO some handling of an already present process
-        m_child->deleteLater();
-    }
-    m_child = new QProcess(this);
-    connect(m_child, static_cast<void (QProcess::*)(int, QProcess::ExitStatus)>(&QProcess::finished), this, &WinDrive::onFinished);
-    connect(m_child, &QProcess::readyRead, this, &WinDrive::onReadyRead);
-    connect(qApp, &QCoreApplication::aboutToQuit, m_child, &QProcess::terminate);
+    // Create new process using unique_ptr
+    m_process.reset(new QProcess(this));
```
Comment (grulja) [inline src/app/windrivemanager.cpp]: `std::make_unique`

Comment (grulja) [reply src/app/windrivemanager.cpp]: And drop the comment.

File: src/app/windrivemanager.cpp [hunk 5]
```diff
@@ -158,38 +149,31 @@ bool WinDrive::write(ReleaseVariant *data)
...
 
 void WinDrive::restore()
 {
     mDebug() << this->metaObject()->className() << "Preparing to restore disk" << m_device;
-    if (m_child)
-        m_child->deleteLater();
-
-    m_child = new QProcess(this);
+    
+    m_process.reset(new QProcess(this));
```
Comment (grulja) [inline src/app/windrivemanager.cpp]: `std::make_unique`

**Comment by Prachi194agrawal** [comment]
Sir,                                                                                                                                                                                                                  I've updated the PR to use std::make_unique and moved the cleanup logic to the base class as suggested—thanks for the helpful guidance. Ready for another review.

**Review by grulja — APPROVED** [review]
Looks good to me. Thanks.

I will do some quick testing later today before I merge this to be sure it works as expected.

**Review by grulja — CHANGES_REQUESTED** [review]
Sorry, you might have to revert the usage of `std::make_unique` as it doesn't work with custom deleter, which I didn't realize (it fails to build).

**Comment by grulja** [comment]
Can you please fix the clang-format issue? You can run clang-format locally to fix it properly. I will get to this next Friday as I will be now on vacation until then.

**Comment by Prachi194agrawal** [comment]
> Can you please fix the clang-format issue? You can run clang-format locally to fix it properly. I will get to this next Friday as I will be now on vacation until then.

Yes, sir.
